# Generated by Django 6.0.2 on 2026-05-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='nota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filme',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
